{% set version = "3.29.0" %}

package:
  name: openmdao
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openmdao/openmdao-{{ version }}.tar.gz
  sha256: ad53004c228e9268cb3f8cf9a61b8a6b3419bab935ab3e0732b948f4bd3fe447

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wingproj = openmdao.devtools.wingproj:run_wing
    - webview = openmdao.utils.webview:webview_argv
    - run_om_test = openmdao.devtools.run_test:run_test
    - openmdao = openmdao.utils.om:openmdao_cmd
    - reset_notebook = openmdao.devtools.docutils:reset_notebook_cmd

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - networkx >=2.0
    - numpy
    - packaging
    - python >=3.7
    - requests
    - scipy

test:
  requires:
    - parameterized
    - numpydoc >=0.9.1
    - pycodestyle >=2.4.0
    - testflo >=1.3.6
    - aiounittest
    # not fully testing viz YET, but does fulfill undocumented tornado dep
    - bokeh >=1.3.4
    - colorama
    - matplotlib-base
    - notebook
    - tabulate
    - pydoe2
    - pyparsing
    # for pip check
    - pip
    # from sphinx
    - jinja2 >=2.3,<3.0
    - markupsafe <2.0
    # for networkx
    - python >=3.9
  imports:
    - openmdao
  commands:
    - python -m pip check
    - openmdao --help
    - webview --help
    - wingproj --help

about:
  home: https://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenMDAO framework infrastructure
  description: |
    OpenMDAO is an open-source high-performance computing platform
    for systems analysis and multidisciplinary optimization, written in Python. It
    enables you to decompose your models, making them easier to build and maintain,
    while still solving them in a tightly coupled manner with efficient parallel
    numerical methods.
  doc_url: https://openmdao.org/twodocs
  dev_url: https://github.com/OpenMDAO/OpenMDAO
  doc_source_url: https://github.com/OpenMDAO/OpenMDAO/tree/master/openmdao/docs

extra:
  recipe-maintainers:
    - bollwyvl
