{% set name = "openmdao" %}
{% set version = "2.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d239ab55f909b33a4db5c952dfd3761da3ab40ecfa3936a32b071b03a984f9b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wingproj  = openmdao.devtools.wingproj:run_wing
    - webview   = openmdao.utils.webview:webview_argv
    - run_om_test  = openmdao.devtools.run_test:run_test
    - openmdao  = openmdao.utils.om:openmdao_cmd

requirements:
  host:
    - python
    - pip
  run:
    - networkx >=2.0
    - numpy
    - pydoe2
    - pyparsing
    - requests
    - scipy
    - six
    - urllib3 <1.25.0a0

test:
  requires:
    - parameterized
    - numpydoc >=0.9.1
    - pycodestyle >=2.4.0
    - pydocstyle ==2.0.0
    - testflo >=1.3.6
    # not fully testing viz YET, but does fulfill undocumented tornado dep
    - bokeh >=1.3.4
    - colorama
    # for pip check
    - pip
  imports:
    - openmdao
  commands:
    - pip check
    - openmdao --help
    - webview --help
    - wingproj --help

about:
  home: https://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: |
    OpenMDAO is an open-source high-performance computing platform
    for systems analysis and multidisciplinary optimization, written in Python.
  description: |
    It enables you to decompose your models, making them easier to build and
    maintain, while still solving them in a tightly coupled manner with
    efficient parallel numerical methods.
  doc_url: https://openmdao.org/twodocs
  dev_url: https://github.com/OpenMDAO/OpenMDAOignore

extra:
  recipe-maintainers:
    - bollwyvl
