{% set name = "openmdao" %}
{% set version = "3.16.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e04af16ff68a068d787f1ea6419709843cf03202b746b1ce9d5eea22c3f7db02

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wingproj = openmdao.devtools.wingproj:run_wing
    - webview = openmdao.utils.webview:webview_argv
    - run_om_test = openmdao.devtools.run_test:run_test
    - openmdao = openmdao.utils.om:openmdao_cmd
    - reset_notebook = openmdao.devtools.docutils:reset_notebook_cmd

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - networkx >=2.0
    - numpy
    - pydoe2
    - pyparsing
    - python >=3.6
    - requests
    - scipy

test:
  requires:
    - parameterized
    - numpydoc >=0.9.1
    - pycodestyle >=2.4.0
    - pydocstyle ==2.0.0
    - testflo >=1.3.6
    - aiounittest
    - pyppeteer
    # not fully testing viz YET, but does fulfill undocumented tornado dep
    - bokeh >=1.3.4
    - colorama
    - matplotlib-base
    - notebook
    - tabulate
    # for pip check
    - pip
    # from sphinx
    - jinja2 >=2.3,<3.0
    - markupsafe <2.0
  imports:
    - openmdao
  commands:
    - python -m pip check
    - openmdao --help
    - webview --help
    - wingproj --help

about:
  home: https://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenMDAO framework infrastructure
  description: |
    OpenMDAO is an open-source high-performance computing platform
    for systems analysis and multidisciplinary optimization, written in Python. It
    enables you to decompose your models, making them easier to build and maintain,
    while still solving them in a tightly coupled manner with efficient parallel
    numerical methods.
  doc_url: https://openmdao.org/twodocs
  dev_url: https://github.com/OpenMDAO/OpenMDAO
  doc_source_url: https://github.com/OpenMDAO/OpenMDAO/tree/master/openmdao/docs

extra:
  recipe-maintainers:
    - bollwyvl
