travis:
  secure:
    BINSTAR_TOKEN: eL+kMX7H6+rqib6ySwCX0cTKmd5IQOlLxaMTxttKj1VIQQPGPxCCiNNcRKT035iPxlujE35OUoNFvNGF5JxG0pf+/G274YdvKrFE3Zv/s4qd02jJU1g7KZWHSh0ozT4/zXyRDJ9e+IT11gSmehtx3NH6K94Xych5DNH/E1sXB4zxn8QmmjgaeYGKTGtmwY0zibG/vDEyyfEHdVaU2TAtS+z5UwQN9B28aRcJOX22tSLg0Jknil0U+8Ynha8lrPqES4K/VPNk9r0IlPfjSHwAL2yeearuzLnWfb6lcy5Dhmph8ithOYbNDEAPwjc/etcTCLZbFFSZ7Nw9VX7k4PFbvp1MM9rLB9VdS+1gkWRMwmG9+C4wFnXBRqHu7NOaT+cmB24Wyq5uZNf9liunl2yG++4xAo6Bxtvvd0z9hMWoL5uSAGjZpyuLE0ON5eDOn1R/BVlHSatylOk90RdDeU7w8/9Q4y7UPdGWbsIEtGajlv8U/+M+GA6V3dZtMXOb0Pv4zkZB7WCi4sSwd2zxLGDdTvAPtOInwL508P1hFkhMfQvX0uHCeZTXId/x2eQJMl82GSzhnwHHxvIWGs8xtOlLt1pfy9BcZXlnRwwMbDiRnR7gPsN2Msi5cFglyI7mAwgnEKfi0W03e1Pl5NPRKnwBv1x1JfcNSc2swb6HOUXz5hs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux: azure
  osx: azure
  win: azure
