travis:
  secure:
    BINSTAR_TOKEN: YhJa2h8ipGfHpiir8/z0lfDGauoWh9gRDiUs4DqtruayVYsfmbKL8jt5M/7yhpgyVe9O8PNwRVuR/cXyrp7iSJM5EP++9RHN32I5DA5uXOXGGC6bczWX9Uwd0ATwcEMKcbc01kTnIn82ZLPNzrnaxTOnl4/DQxzAc2dWE71q/tUPb7NpaS2dAkIBM5KbHZE9CkDDYO2aIC2BC6Uz7HxXen+NNDm+H0V2jBoe4jyqJTo8YAjTnhy2Chan7iiEuXXr6GC9+TrlQnnOrWaO19i90OtkVmK1c1z6Dl8cnr3jHhX+ZoaZOJemOkEVjNMddZiCHHzF8TW9ZYdCYHUTo4OT32YqP19WdPo/MmSWtlKjJUSDiypTuzZ8+Fe5eTl5Sv8OVEMGSXLjm8juya8nurfN3Gjs27vPpFkha0xb4rS57Jfy0txOS62cQ7MDANzldq826hTvpmWY08U1p6Wk2LdSPfSM4DUnoxb5wD4katWVzh23cP/lMRd7gsRkdYxGQd43s8Smj0VM31WDKKAPXgzGep07PK84c0AQ6ZNiqdov5TLaJI1LXhZ0vU2WoKZ54etzvPKAAa3AgFbRQ3CBY0RbJK6XHpFVEgkI2jUUY0bEUB2npK88gEFPMU2SmivC56JFhIYobSCv7cBWY4TVCqJp6Q+8LZqYx6/i1UT4n48BWJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
